{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "2ff9b213-aaa7-49d4-bfab-d0b283b2533b",
   "metadata": {},
   "outputs": [],
   "source": [
    "# !pip install fiona\n",
    "import folium\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "d21dcb6b-5e7e-4221-9eac-fc9d007e87f8",
   "metadata": {},
   "outputs": [],
   "source": [
    "# m = folium.Map(location=[0, 0], zoom_start=2)\n",
    "# m"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "53a378fe-5a34-4ddd-aa80-df6e8365c936",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting geopandas\n",
      "  Using cached geopandas-0.12.2-py3-none-any.whl (1.1 MB)\n",
      "Collecting shapely>=1.7\n",
      "  Using cached shapely-2.0.0-cp39-cp39-macosx_11_0_arm64.whl (1.2 MB)\n",
      "Collecting pyproj>=2.6.1.post1\n",
      "  Using cached pyproj-3.4.1-cp39-cp39-macosx_11_0_arm64.whl (5.7 MB)\n",
      "Collecting fiona>=1.8\n",
      "  Using cached Fiona-1.8.22.tar.gz (1.4 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/moidshaikh/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_d99a0ca9a9d240ed94cbfc1f8e18caf8/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_d99a0ca9a9d240ed94cbfc1f8e18caf8/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-pip-egg-info-8bu6ibhs\n",
      "         cwd: /private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_d99a0ca9a9d240ed94cbfc1f8e18caf8/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/b9/d7/48025179fbbb2e1bab698131246878df36fa9aa5bee0ba1c062cd8f2ef44/Fiona-1.8.22.tar.gz#sha256=a82a99ce9b3e7825740157c45c9fb2259d4e92f0a886aaac25f0db40ffe1eea3 (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.21.tar.gz (1.0 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/moidshaikh/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_5a616ae7482f4ac7b3ab5e45e45fc0d6/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_5a616ae7482f4ac7b3ab5e45e45fc0d6/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-pip-egg-info-nwsc5unr\n",
      "         cwd: /private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_5a616ae7482f4ac7b3ab5e45e45fc0d6/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/67/5c/4e028e84a1f0cb3f8a994217cf2366360ca984dfc1433f6171de527d0dca/Fiona-1.8.21.tar.gz#sha256=3a0edca2a7a070db405d71187214a43d2333a57b4097544a3fcc282066a58bfc (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.20.tar.gz (1.3 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/moidshaikh/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_5edc1780a25a4fa4a2cc8087ff50c388/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_5edc1780a25a4fa4a2cc8087ff50c388/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-pip-egg-info-_5ffgcji\n",
      "         cwd: /private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_5edc1780a25a4fa4a2cc8087ff50c388/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/ec/f7/093890341a7e8fbfcdfa04caf4dfb588ebab32c13ceaa6a3819da79ea106/Fiona-1.8.20.tar.gz#sha256=a70502d2857b82f749c09cb0dea3726787747933a2a1599b5ab787d74e3c143b (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.19.tar.gz (1.3 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/moidshaikh/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_c8ed553b4c0d4bcc95ea0366a96fd681/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_c8ed553b4c0d4bcc95ea0366a96fd681/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-pip-egg-info-18k0srsk\n",
      "         cwd: /private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_c8ed553b4c0d4bcc95ea0366a96fd681/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/a0/d9/6042aeb073d11341f7726de0586ff71c13117c34959dcf07bd4ee6d4b93e/Fiona-1.8.19.tar.gz#sha256=b9059e0b29c2e9e6b817e53f941e77e1aca7075f986005d38db307067b60458f (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.18.tar.gz (1.3 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/moidshaikh/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_d088d1cf5cf44690945d604ec302919a/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_d088d1cf5cf44690945d604ec302919a/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-pip-egg-info-tmgva_ue\n",
      "         cwd: /private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_d088d1cf5cf44690945d604ec302919a/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/9f/e8/401cdaa58d862a25c4b3365acf7d2bd7ac77191e3dc9acdcdac0eff20ff0/Fiona-1.8.18.tar.gz#sha256=b732ece0ff8886a29c439723a3e1fc382718804bb057519d537a81308854967a (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.17.tar.gz (1.3 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/moidshaikh/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_88251c975a7e4a38a2056c8bcd0c724e/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_88251c975a7e4a38a2056c8bcd0c724e/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-pip-egg-info-00qp06_1\n",
      "         cwd: /private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_88251c975a7e4a38a2056c8bcd0c724e/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/88/62/69347ba2c41b526e1953c4cb66d51170b2869808863c03af202ba0121670/Fiona-1.8.17.tar.gz#sha256=716201c21246587f374785bec6d6a20a984fe1f6c2b0e83bf15127eb8f724d0c (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.16.tar.gz (1.3 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/moidshaikh/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_ed7e2299433d42329a9626b392b80617/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_ed7e2299433d42329a9626b392b80617/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-pip-egg-info-ng06pc5b\n",
      "         cwd: /private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_ed7e2299433d42329a9626b392b80617/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/1e/60/dfc6115a11338d8aa96cacd8c60635223d9c97d61d556c90acc5dfd663fa/Fiona-1.8.16.tar.gz#sha256=fd6dfb65959becc916e9f6928618bfd59c16cdbc413ece0fbac61489cd11255f (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.15.tar.gz (1.3 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/moidshaikh/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_c270ee68e64e448ab4fad1d41d60e910/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_c270ee68e64e448ab4fad1d41d60e910/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-pip-egg-info-tv0zpzpz\n",
      "         cwd: /private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_c270ee68e64e448ab4fad1d41d60e910/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/55/2f/17450ec2c8fcc720a8a3e4d9a383499508475c7cfb90f7eca9fb585ac598/Fiona-1.8.15.tar.gz#sha256=3b1c9b5c834fae2fe947cfaea176db890bc6750d1a6ba9f54d969c19ffcd191e (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.14.tar.gz (1.3 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/moidshaikh/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_ecb155303a194696b7359326fa62ecd9/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_ecb155303a194696b7359326fa62ecd9/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-pip-egg-info-e1tb1oub\n",
      "         cwd: /private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_ecb155303a194696b7359326fa62ecd9/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/5c/fd/5ec54f2d9b3d5dd23dd443fad5630d6b872e2664814c68b856c47e0d65af/Fiona-1.8.14.tar.gz#sha256=6eac038206c89d2cf5f99ea38b81cc228dc21eac5f47870a9a32d453b0007f4d (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.13.post1.tar.gz (1.2 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/moidshaikh/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_09e4ed249a6440c0a0d403dee39250e9/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_09e4ed249a6440c0a0d403dee39250e9/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-pip-egg-info-zfcp7yri\n",
      "         cwd: /private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_09e4ed249a6440c0a0d403dee39250e9/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/6d/42/f4a7cac53b28fa70e9a93d0e89a24d33e14826dad6644b699362ad84dde0/Fiona-1.8.13.post1.tar.gz#sha256=1a432bf9fd56f089256c010da009c90d4a795c531a848132c965052185336600 (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.13.tar.gz (1.2 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/moidshaikh/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_63ebf51f19064f188b773b92fae0a816/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_63ebf51f19064f188b773b92fae0a816/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-pip-egg-info-fot8ezv6\n",
      "         cwd: /private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_63ebf51f19064f188b773b92fae0a816/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/be/04/31d0a6f03943b1684f32c9b861be40c1fd282468fa6bd54ddf4a774e6b0f/Fiona-1.8.13.tar.gz#sha256=5ec34898c8b983a723fb4e949dd3e0ed7e691c303e51f6bfd61e52ac9ac813ae (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.12.tar.gz (1.2 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/moidshaikh/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_9a7b8e7809db45a7be4538eca1db056e/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_9a7b8e7809db45a7be4538eca1db056e/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-pip-egg-info-nrtj1j79\n",
      "         cwd: /private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_9a7b8e7809db45a7be4538eca1db056e/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/97/d8/feab39987296437fbdc3029fb39752a14355d217d73b93471010b8dd63a3/Fiona-1.8.12.tar.gz#sha256=c9266ddf6ae2a64fcea20014ddf27f800ac07584f2fdb09c2a02f3b3a52e371c (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.11.tar.gz (1.2 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/moidshaikh/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_eb2740fbe7664c79a43f7695357e9412/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_eb2740fbe7664c79a43f7695357e9412/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-pip-egg-info-uxw_2270\n",
      "         cwd: /private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_eb2740fbe7664c79a43f7695357e9412/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/9d/f4/0a0ddc6174c4a93679b5f1dd3535e7ef8989828e6d5f86112de681f8c87b/Fiona-1.8.11.tar.gz#sha256=1e7ca9e051f5bffa1c43c70d573da9ca223fc076b84fa73380614fc02b9eb7f6 (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.10.tar.gz (1.2 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/moidshaikh/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_f3bc131c9d7e4400a1d0c8fffeaea790/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_f3bc131c9d7e4400a1d0c8fffeaea790/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-pip-egg-info-5qw77toh\n",
      "         cwd: /private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_f3bc131c9d7e4400a1d0c8fffeaea790/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/13/73/f80b491ed8559326fab202a6d6333a3cd6e8be1e9d782bc6c0d03d476457/Fiona-1.8.10.tar.gz#sha256=ff562eb2f3960e21f8c7f050ddd7f47a763869ea14afc2234a40df72666c6a2c (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.9.post2.tar.gz (1.2 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/moidshaikh/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_3252a607527f4da9a310724447d6e377/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_3252a607527f4da9a310724447d6e377/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-pip-egg-info-ks_b8qgg\n",
      "         cwd: /private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_3252a607527f4da9a310724447d6e377/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/9b/52/45e75507660ce0e86176d0f59b659560f687e2c7e9ebf82a10e7dcd2d3b7/Fiona-1.8.9.post2.tar.gz#sha256=210fb038b579fab38f35ddbdd31b9725f4d5099b3edfd4b87c983e5d47b79983 (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.9.post1.tar.gz (1.2 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/moidshaikh/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_e4b3fa7b0e4a4feab88a918ed79b9e67/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_e4b3fa7b0e4a4feab88a918ed79b9e67/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-pip-egg-info-h2c4h3co\n",
      "         cwd: /private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_e4b3fa7b0e4a4feab88a918ed79b9e67/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/0e/a4/d9dd7399be809d3990f5000fb6ae43189ea26ae88be1bed3a4c9ddc1becc/Fiona-1.8.9.post1.tar.gz#sha256=d5e0ea0b8addffe9cba4cb59e2bd495b015230e7a1b1597974f5048211930199 (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.9.tar.gz (1.2 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/moidshaikh/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_7aeffd6840964567960f1ab7b0c0456e/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_7aeffd6840964567960f1ab7b0c0456e/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-pip-egg-info-m2bbmmi6\n",
      "         cwd: /private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_7aeffd6840964567960f1ab7b0c0456e/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/ad/92/dcbd8c54d697c22f299b5af63b6df3acfbd06c6d72e249614c05be99337c/Fiona-1.8.9.tar.gz#sha256=4dd6e2f5327c1174143c7c8594a75d373bc72f2c9a2a6daee312c3186a128add (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.8.tar.gz (1.7 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/moidshaikh/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_bd5bd5d382cb497382b5336ff0d9bf6a/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_bd5bd5d382cb497382b5336ff0d9bf6a/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-pip-egg-info-4d5sjz2h\n",
      "         cwd: /private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_bd5bd5d382cb497382b5336ff0d9bf6a/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/94/7f/e288db1ad63d759d494c30caae34f865e0c6927588c490705e91b7134193/Fiona-1.8.8.tar.gz#sha256=711c3be73203b37812992089445a1e4e9d3d6b64e667389f7b15406e15a91e83 (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.7.tar.gz (1.7 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/moidshaikh/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_b09455e0cda54b59868282d82cc33896/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_b09455e0cda54b59868282d82cc33896/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-pip-egg-info-subnq66y\n",
      "         cwd: /private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_b09455e0cda54b59868282d82cc33896/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/78/62/daafd070aebefa639df247705b97f13f7cfad43895581b5cae41bd886709/Fiona-1.8.7.tar.gz#sha256=a55a23615bad3e142d4e4cda97bb5de83c778a80049222e9dffae93c13b5cf93 (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.6.tar.gz (1.7 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/moidshaikh/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_939e0d4ff1534ab08d6247033a9716dc/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_939e0d4ff1534ab08d6247033a9716dc/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-pip-egg-info-g5p9kwun\n",
      "         cwd: /private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_939e0d4ff1534ab08d6247033a9716dc/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/41/9d/63696e7b1de42aad294d4781199a408bec593d8fdb80a2b4a788c911a33b/Fiona-1.8.6.tar.gz#sha256=fa31dfe8855b9cd0b128b47a4df558f1b8eda90d2181bff1dd9854e5556efb3e (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.5.tar.gz (1.7 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/moidshaikh/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_5059275819364c77a4cb615111e4f368/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_5059275819364c77a4cb615111e4f368/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-pip-egg-info-0rcsmtlh\n",
      "         cwd: /private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_5059275819364c77a4cb615111e4f368/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/7b/af/1c2c83c4a8363a4ce9fea817b1910b5e071bed012e18257faa2a0ab3cfe7/Fiona-1.8.5.tar.gz#sha256=4f5cc2d449edbbf693c83e24cdada72de7c41297383d16fcc92387eb445e9d35 (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.4.tar.gz (1.1 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/moidshaikh/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_35c84ef187434982a2da05701709333a/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_35c84ef187434982a2da05701709333a/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-pip-egg-info-29ozcz7b\n",
      "         cwd: /private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_35c84ef187434982a2da05701709333a/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/3a/16/84960540e9fce61d767fd2f0f1d95f4c63e99ab5d8fddc308e8b51b059b8/Fiona-1.8.4.tar.gz#sha256=aec9ab2e3513c9503ec123b1a8573bee55fc6a66e2ac07088c3376bf6738a424 (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.3.tar.gz (1.1 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/moidshaikh/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_dedb72213d8d4b6f8d5df9e99852555c/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_dedb72213d8d4b6f8d5df9e99852555c/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-pip-egg-info-nj0h1ql3\n",
      "         cwd: /private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_dedb72213d8d4b6f8d5df9e99852555c/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/46/d1/fcdb32513a03abfde0d97fd9782ce0f8cc0540fa6c6ce783e87b94064964/Fiona-1.8.3.tar.gz#sha256=3e831100a23c3b6cd32b98baf0c9e2119d909b44a5cf4533d3625f61dcf2d2b1 (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.2.tar.gz (1.2 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/moidshaikh/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_bc22d04936f14695ab0e470ee888cc1e/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_bc22d04936f14695ab0e470ee888cc1e/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-pip-egg-info-dveld4q8\n",
      "         cwd: /private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_bc22d04936f14695ab0e470ee888cc1e/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/25/50/0466d5d83e1859c5ca38351ee932d64cc5635f9d4dad522879e58f4b0018/Fiona-1.8.2.tar.gz#sha256=4c6419b7ac29136708029f6a44b4ccd458735a4d241016c7b1bab41685c08d8f (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.1.tar.gz (1.1 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/moidshaikh/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_612c8a339d2d4a56bd3deed6baa79b66/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_612c8a339d2d4a56bd3deed6baa79b66/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-pip-egg-info-ag6tdwk2\n",
      "         cwd: /private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_612c8a339d2d4a56bd3deed6baa79b66/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/3e/5f/0c6704efeea2ff3fba7f54cc6ec38070157f21bc1cffa7bdfa7c9f6b8f7a/Fiona-1.8.1.tar.gz#sha256=4c34bb4c5cd788aaf14e5484c3b7de407b1a8a7c7b2d29bbb2e8b37931e83b8d (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.0.tar.gz (1.4 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/moidshaikh/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_f60b14f176914dd5af185e886377655a/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_f60b14f176914dd5af185e886377655a/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-pip-egg-info-wwto3itr\n",
      "         cwd: /private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_f60b14f176914dd5af185e886377655a/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/2a/bd/c1efc2680f338e5941121c776d6323af6b9698ac739e22ba523cee348a7f/Fiona-1.8.0.tar.gz#sha256=20141a9ece06daa7bb4333fba640c2fe39a49f8aca5492d1da8595d41e91844a (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "Collecting geopandas\n",
      "  Using cached geopandas-0.12.1-py3-none-any.whl (1.1 MB)\n",
      "  Using cached geopandas-0.12.0-py3-none-any.whl (1.1 MB)\n",
      "Collecting shapely<2,>=1.7\n",
      "  Using cached Shapely-1.8.5.post1-cp39-cp39-macosx_11_0_arm64.whl (1.1 MB)\n",
      "Collecting geopandas\n",
      "  Using cached geopandas-0.11.1-py3-none-any.whl (1.0 MB)\n",
      "  Using cached geopandas-0.11.0-py3-none-any.whl (1.0 MB)\n",
      "  Using cached geopandas-0.10.2-py2.py3-none-any.whl (1.0 MB)\n",
      "Requirement already satisfied: pandas>=0.25.0 in /Users/moidshaikh/opt/anaconda3/lib/python3.9/site-packages (from geopandas) (1.4.2)\n",
      "  Using cached geopandas-0.10.1-py2.py3-none-any.whl (1.0 MB)\n",
      "  Using cached geopandas-0.10.0-py2.py3-none-any.whl (1.0 MB)\n",
      "  Using cached geopandas-0.9.0-py2.py3-none-any.whl (994 kB)\n",
      "  Using cached geopandas-0.8.2-py2.py3-none-any.whl (962 kB)\n",
      "Collecting fiona\n",
      "  Using cached Fiona-1.7.13.tar.gz (731 kB)\n",
      "Requirement already satisfied: python-dateutil>=2.8.1 in /Users/moidshaikh/opt/anaconda3/lib/python3.9/site-packages (from pandas>=0.25.0->geopandas) (2.8.2)\n",
      "Requirement already satisfied: pytz>=2020.1 in /Users/moidshaikh/opt/anaconda3/lib/python3.9/site-packages (from pandas>=0.25.0->geopandas) (2021.3)\n",
      "Requirement already satisfied: numpy>=1.20.0 in /Users/moidshaikh/opt/anaconda3/lib/python3.9/site-packages (from pandas>=0.25.0->geopandas) (1.21.5)\n",
      "Requirement already satisfied: certifi in /Users/moidshaikh/opt/anaconda3/lib/python3.9/site-packages (from pyproj>=2.6.1.post1->geopandas) (2022.5.18.1)\n",
      "Requirement already satisfied: six>=1.5 in /Users/moidshaikh/opt/anaconda3/lib/python3.9/site-packages (from python-dateutil>=2.8.1->pandas>=0.25.0->geopandas) (1.16.0)\n",
      "Requirement already satisfied: cligj>=0.4 in /Users/moidshaikh/opt/anaconda3/lib/python3.9/site-packages (from fiona->geopandas) (0.7.2)\n",
      "Requirement already satisfied: click-plugins in /Users/moidshaikh/opt/anaconda3/lib/python3.9/site-packages (from fiona->geopandas) (1.1.1)\n",
      "Requirement already satisfied: munch in /Users/moidshaikh/opt/anaconda3/lib/python3.9/site-packages (from fiona->geopandas) (2.5.0)\n",
      "Requirement already satisfied: click>=4.0 in /Users/moidshaikh/opt/anaconda3/lib/python3.9/site-packages (from cligj>=0.4->fiona->geopandas) (8.0.4)\n",
      "Building wheels for collected packages: fiona\n",
      "  Building wheel for fiona (setup.py) ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /Users/moidshaikh/opt/anaconda3/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_83db7fd737c94592aaf587321b10cdf8/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_83db7fd737c94592aaf587321b10cdf8/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' bdist_wheel -d /private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-wheel-1shvvfg3\n",
      "       cwd: /private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_83db7fd737c94592aaf587321b10cdf8/\n",
      "  Complete output (50 lines):\n",
      "  Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "  /Users/moidshaikh/opt/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/dist.py:275: UserWarning: Unknown distribution option: 'metadata_version'\n",
      "    warnings.warn(msg)\n",
      "  /Users/moidshaikh/opt/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/dist.py:275: UserWarning: Unknown distribution option: 'requires_python'\n",
      "    warnings.warn(msg)\n",
      "  /Users/moidshaikh/opt/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/dist.py:275: UserWarning: Unknown distribution option: 'requires_external'\n",
      "    warnings.warn(msg)\n",
      "  running bdist_wheel\n",
      "  running build\n",
      "  running build_py\n",
      "  creating build\n",
      "  creating build/lib.macosx-11.1-arm64-3.9\n",
      "  creating build/lib.macosx-11.1-arm64-3.9/fiona\n",
      "  copying ./fiona/compat.py -> build/lib.macosx-11.1-arm64-3.9/fiona\n",
      "  copying ./fiona/drvsupport.py -> build/lib.macosx-11.1-arm64-3.9/fiona\n",
      "  copying ./fiona/inspector.py -> build/lib.macosx-11.1-arm64-3.9/fiona\n",
      "  copying ./fiona/__init__.py -> build/lib.macosx-11.1-arm64-3.9/fiona\n",
      "  copying ./fiona/crs.py -> build/lib.macosx-11.1-arm64-3.9/fiona\n",
      "  copying ./fiona/rfc3339.py -> build/lib.macosx-11.1-arm64-3.9/fiona\n",
      "  copying ./fiona/transform.py -> build/lib.macosx-11.1-arm64-3.9/fiona\n",
      "  copying ./fiona/collection.py -> build/lib.macosx-11.1-arm64-3.9/fiona\n",
      "  copying ./fiona/errors.py -> build/lib.macosx-11.1-arm64-3.9/fiona\n",
      "  copying ./fiona/tool.py -> build/lib.macosx-11.1-arm64-3.9/fiona\n",
      "  creating build/lib.macosx-11.1-arm64-3.9/fiona/fio\n",
      "  copying ./fiona/fio/options.py -> build/lib.macosx-11.1-arm64-3.9/fiona/fio\n",
      "  copying ./fiona/fio/collect.py -> build/lib.macosx-11.1-arm64-3.9/fiona/fio\n",
      "  copying ./fiona/fio/distrib.py -> build/lib.macosx-11.1-arm64-3.9/fiona/fio\n",
      "  copying ./fiona/fio/env.py -> build/lib.macosx-11.1-arm64-3.9/fiona/fio\n",
      "  copying ./fiona/fio/insp.py -> build/lib.macosx-11.1-arm64-3.9/fiona/fio\n",
      "  copying ./fiona/fio/cat.py -> build/lib.macosx-11.1-arm64-3.9/fiona/fio\n",
      "  copying ./fiona/fio/__init__.py -> build/lib.macosx-11.1-arm64-3.9/fiona/fio\n",
      "  copying ./fiona/fio/ls.py -> build/lib.macosx-11.1-arm64-3.9/fiona/fio\n",
      "  copying ./fiona/fio/dump.py -> build/lib.macosx-11.1-arm64-3.9/fiona/fio\n",
      "  copying ./fiona/fio/calc.py -> build/lib.macosx-11.1-arm64-3.9/fiona/fio\n",
      "  copying ./fiona/fio/filter.py -> build/lib.macosx-11.1-arm64-3.9/fiona/fio\n",
      "  copying ./fiona/fio/load.py -> build/lib.macosx-11.1-arm64-3.9/fiona/fio\n",
      "  copying ./fiona/fio/main.py -> build/lib.macosx-11.1-arm64-3.9/fiona/fio\n",
      "  copying ./fiona/fio/info.py -> build/lib.macosx-11.1-arm64-3.9/fiona/fio\n",
      "  copying ./fiona/fio/helpers.py -> build/lib.macosx-11.1-arm64-3.9/fiona/fio\n",
      "  copying ./fiona/fio/bounds.py -> build/lib.macosx-11.1-arm64-3.9/fiona/fio\n",
      "  running build_ext\n",
      "  building 'fiona._transform' extension\n",
      "  creating build/temp.macosx-11.1-arm64-3.9\n",
      "  creating build/temp.macosx-11.1-arm64-3.9/fiona\n",
      "  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/moidshaikh/opt/anaconda3/include -arch arm64 -I/Users/moidshaikh/opt/anaconda3/include -fPIC -O2 -isystem /Users/moidshaikh/opt/anaconda3/include -arch arm64 -I/Users/moidshaikh/opt/anaconda3/include/python3.9 -c fiona/_transform.cpp -o build/temp.macosx-11.1-arm64-3.9/fiona/_transform.o\n",
      "  fiona/_transform.cpp:606:10: fatal error: 'cpl_conv.h' file not found\n",
      "  #include \"cpl_conv.h\"\n",
      "           ^~~~~~~~~~~~\n",
      "  1 error generated.\n",
      "  error: command '/usr/bin/clang' failed with exit code 1\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[31m  ERROR: Failed building wheel for fiona\u001b[0m\n",
      "\u001b[?25h  Running setup.py clean for fiona\n",
      "Failed to build fiona\n",
      "Installing collected packages: shapely, pyproj, fiona, geopandas\n",
      "    Running setup.py install for fiona ... \u001b[?25lerror\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/moidshaikh/opt/anaconda3/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_83db7fd737c94592aaf587321b10cdf8/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_83db7fd737c94592aaf587321b10cdf8/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' install --record /private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-record-xqu_6wh1/install-record.txt --single-version-externally-managed --compile --install-headers /Users/moidshaikh/opt/anaconda3/include/python3.9/fiona\n",
      "         cwd: /private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_83db7fd737c94592aaf587321b10cdf8/\n",
      "    Complete output (22 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    /Users/moidshaikh/opt/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/dist.py:275: UserWarning: Unknown distribution option: 'metadata_version'\n",
      "      warnings.warn(msg)\n",
      "    /Users/moidshaikh/opt/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/dist.py:275: UserWarning: Unknown distribution option: 'requires_python'\n",
      "      warnings.warn(msg)\n",
      "    /Users/moidshaikh/opt/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/dist.py:275: UserWarning: Unknown distribution option: 'requires_external'\n",
      "      warnings.warn(msg)\n",
      "    running install\n",
      "    /Users/moidshaikh/opt/anaconda3/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.\n",
      "      warnings.warn(\n",
      "    running build\n",
      "    running build_py\n",
      "    running build_ext\n",
      "    building 'fiona._transform' extension\n",
      "    creating build/temp.macosx-11.1-arm64-3.9\n",
      "    creating build/temp.macosx-11.1-arm64-3.9/fiona\n",
      "    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/moidshaikh/opt/anaconda3/include -arch arm64 -I/Users/moidshaikh/opt/anaconda3/include -fPIC -O2 -isystem /Users/moidshaikh/opt/anaconda3/include -arch arm64 -I/Users/moidshaikh/opt/anaconda3/include/python3.9 -c fiona/_transform.cpp -o build/temp.macosx-11.1-arm64-3.9/fiona/_transform.o\n",
      "    fiona/_transform.cpp:606:10: fatal error: 'cpl_conv.h' file not found\n",
      "    #include \"cpl_conv.h\"\n",
      "             ^~~~~~~~~~~~\n",
      "    1 error generated.\n",
      "    error: command '/usr/bin/clang' failed with exit code 1\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[31mERROR: Command errored out with exit status 1: /Users/moidshaikh/opt/anaconda3/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_83db7fd737c94592aaf587321b10cdf8/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-install-ti6sc686/fiona_83db7fd737c94592aaf587321b10cdf8/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' install --record /private/var/folders/df/8_qds2ns5t50hs447k_yybv80000gn/T/pip-record-xqu_6wh1/install-record.txt --single-version-externally-managed --compile --install-headers /Users/moidshaikh/opt/anaconda3/include/python3.9/fiona Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h"
     ]
    },
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'geopandas'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
      "Input \u001b[0;32mIn [18]\u001b[0m, in \u001b[0;36m<cell line: 2>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      1\u001b[0m get_ipython()\u001b[38;5;241m.\u001b[39msystem(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mpip install geopandas\u001b[39m\u001b[38;5;124m'\u001b[39m)\n\u001b[0;32m----> 2\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01mgeopandas\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m \u001b[38;5;21;01mgpd\u001b[39;00m\n\u001b[1;32m      3\u001b[0m world \u001b[38;5;241m=\u001b[39m gpd\u001b[38;5;241m.\u001b[39mread_file(gpd\u001b[38;5;241m.\u001b[39mdatasets\u001b[38;5;241m.\u001b[39mget_path(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mnaturalearth_lowres\u001b[39m\u001b[38;5;124m'\u001b[39m))\n\u001b[1;32m      4\u001b[0m world\u001b[38;5;241m.\u001b[39mplot()\n",
      "\u001b[0;31mModuleNotFoundError\u001b[0m: No module named 'geopandas'"
     ]
    }
   ],
   "source": [
    "!pip install geopandas\n",
    "import geopandas as gpd\n",
    "world = gpd.read_file(gpd.datasets.get_path('naturalearth_lowres'))\n",
    "world.plot()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "07784680-851c-4654-beae-c7967c6301d9",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
